### ISSUE TITLE
Webpack fails to compile

### ISSUE THREAD

**Issue by Chocbanana** [rescripts/rescripts#9] opened 2018-12-28 21:41 UTC
I'm getting this error when running `npm start`:
```
> rescripts start

Failed to compile.

Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration should be an object.
```
I am using `@rescripts/rescript-use-babel-config@rescripts/rescript-use-babel-config`, followed the directions in the main README and put this in my `package.json`: 
```
  "rescripts": [
    "use-babel-config"
  ]
```
and then added a `.babelrc` to root:
```
{
    "presets": ["stage-0"],
    "plugins": ["@babel/plugin-proposal-decorators"]
}
```

Not sure what's going wrong, and what config webpack is complaining about not being an object...
Additionally, I see in the readme for `@rescripts/rescript-use-babel-config` that for usage you say to put `[["use-babel-config", ".babelrc"]]` in .babelrc, but I'm not sure where that would go?

**Comment by harrysolovay** [comment] 2018-12-28 22:07
Hi @Chocbanana –– that's most likely the problem. Try updating your `package.json`:

```diff
"rescripts": [
- "use-babel-config"
+ ["use-babel-config", ".babelrc"]
]
```

If this doesn't resolve the problem, please let me know. There were some breaking changes a few days ago when the React team merged a PR that combines the development and production configs for webpack. In the case that this is the cause of the problem, please make sure that `react-scripts` and all `@rescripts` packages are up to date.

Let me know how it goes :)

**Comment by harrysolovay** [comment] 2018-12-29 17:08
@chocbanana — I expect this to fix your problem. Gonna close this issue. Feel free to reopen if you need further assistance 👍

**Closed by harrysolovay** 2018-12-29 17:08 UTC

**Comment by Chocbanana** [comment] 2018-12-30 17:48
Worked! If you could update the main README with this info that would be great :)

**Comment by harrysolovay** [comment] 2018-12-30 22:59
@Chocbanana it's already mentioned beneath the installation step
